### ISSUE TITLE
plugin.video.zoomby.ru-0.1.1

### ISSUE THREAD

**Issue by seppius-xbmc-repo** [seppius-xbmc-repo/ru#15]
В архив упакован addons.xml 0.1.0
 и ERROR: EXCEPTION Thrown (PythonToCppException)
http://xbmclogs.com/p6uys7odq

**Comment by undeman** [comment]
Исправил, beautifulsoup4 пытался представить страницу, как xml документ. Такое только на ubuntu было.
Спасибо.

**Comment by seppius-xbmc-repo** [comment]
Работает. Спасибо.
