### ISSUE TITLE
не работает plugin.video.shikimori.org

### ISSUE THREAD

**Issue by KostanKettch** [seppius-xbmc-repo/ru#21]
Собственно сабж.
В логах выдает это:

>Error Type: <type 'exceptions.TypeError'>

>Error Contents: 'NoneType' object has no attribute '__getitem__'

>Traceback (most recent call last):

>File "/home/radakettch/.kodi/addons/plugin.video.shikimori.org/default.py", line 278, in <module>

> if mode == None: Main(url)

>File "/home/radakettch/.kodi/addons/plugin.video.shikimori.org/default.py", line 71, in Main

> 	title = block['data-title'].encode('utf-8')

> TypeError: 'NoneType' object has no attribute '__getitem__'

> -->End of Python script error report<--

> 03:43:53 T:140650418714624   ERROR: GetDirectory - Error getting plugin://plugin.video.shikimori.org/

> 03:43:53 T:140650418714624   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.shikimori.org/) failed

**Comment by undeman** [comment]
Исправил

**Comment by KostanKettch** [comment]
Спасибо. Кстати, есть вопрос: можно ли переделать логику (сейчас "сериал/серия/перевод"), что бы серии можно было смотреть списком ("сериал/перевод/серия") или это специфика сайта?

**Comment by undeman** [comment]
Это особенность сайта, там выбор идёт серии, а потом уже озвучки
