### ISSUE TITLE
No 720p support :(

### ISSUE THREAD

**Issue by andyzasl** [seppius-xbmc-repo/ru#27]
Например фильм: http://www.ivi.ru/watch/74862
в kodi 16 - только SD качество

**Comment by NuisMons** [comment]
Плагин выдает только то, что разрешено для нашей площадки.

**Comment by andyzasl** [comment]
всмысле это ivi.ru не разрешает вам показывать 720p?

**Comment by NuisMons** [comment]
да

**Comment by NuisMons** [comment]
плагин морально устарел, но всегда сам выбирает наилучшее качество, насколько я помню. Когда появились фильмы в HD я смотрел, что иви выдает, для нас HD качества не было
