### ISSUE TITLE
не работает plugin.video.shikimori.org походит на #21

### ISSUE THREAD

**Issue by MrFree** [seppius-xbmc-repo/ru#28]
`22:19:59

 T:140584790324992   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'NoneType' object has no attribute 'getText'
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/plugin.video.shikimori.org/default.py", line 288, in <module>
                                                if mode == None:Main(url)
                                              File "/home/xbmc/.kodi/addons/plugin.video.shikimori.org/default.py", line 75, in Main
                                                title_block = num.find(['a', 'span'], attrs={'class': 'title'}).getText().encode('utf-8')
                                            AttributeError: 'NoneType' object has no attribute 'getText'
                                            -->End of Python script error report<--
22:19:59 T:140587161049472   ERROR: GetDirectory - Error getting plugin://plugin.video.shikimori.org/
22:19:59 T:140587161049472   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.shikimori.org/) failed`

обновлял систему (убунту 16,04,1), отвалилось несколько расширений, в том числе и это.
коди 16,1 был. После обновления до 17b2 и установки в чистый профиль изменений нет.
 Явно какой то пакет снесло, но какой?

**Comment by undeman** [comment]
Залил исправления, протокол сменили и немного разметку поменяли на сайте

**Comment by MrFree** [comment]
Заработало O_0
