### ISSUE TITLE
Ошибка в fix_broken_json(data):

### ISSUE THREAD

**Issue by ghost** [seppius-xbmc-repo/ru#29]
сейчас 
fix_broken_json("{parent_id: 'season:1'}") = > {"parent_id": ""season":1"}

Для фикса 
def fix_broken_json(data):  
    data = re.sub(r'{(\w+):', r'{"\1":', data)
    data = data.replace(': \'', ': "')
    data = data.replace('\',', '",')
    data = data.replace('\'}', '"}')
    data = re.sub(r', (\w+): ', r', "\1":', data)
    return data

**Comment by seppius-xbmc-repo** [comment]
В strutils.py fs.ua  за исключением предпоследней строки в остальном также.

**Comment by eugen-pavlenko-pf** [comment]
Не совсем, в первой строке в шаблон добавлен символ **{**
