### ISSUE TITLE
Music Library Broke

### ISSUE THREAD

**Issue by TheClown1234** [seppius-xbmc-repo/ru#30]
I add the source and path as usual using skin settings but it will not populate into the library.  It is present but still shows on home screen that nothing is added.  Can you look into this please and thank you.

**Comment by seppius-xbmc-repo** [comment]
plugin has a name?

**Comment by TheClown1234** [comment]
mp3 streams which is the only music addon that works with kodi.  Paths are correct and show when going under files/Music/my mp3.  It says on home screen that there is nothing added and give option to add but doesnt.  I have even tried scan to library and it does nothing.  Thought I would mention it.  I know this is a fork of the original skin and the bug might be in both skins.  There is only one music addon out there that works with kodi library.  It works on other skins that I use like Rapier but would like this skin to be the one I use on my box.  Thanks for your hard work and help.  Take care.
