### ISSUE TITLE
plugin.video.shikimori.org Обозначение навания команды дабберов и источника

### ISSUE THREAD

**Issue by iG8R** [seppius-xbmc-repo/ru#44]
Возможно ли обозначить названия команды дабберов и источников видео в самом начале названия файлов?
А еще круче было бы ввести опцию сортировки, когда предпочтительный источник и дабберы располагались более высоко в списке и обозначать их выделяющимся цветом.
Дело в том, что сейчас данные названия находятся в самом конце, потому требуется время для скроллинга(шифтинга?) названия, чтобы понять откуда и от какой команды смотреть видео.

Дополнительный вопрос - возможно ли информацию хранить в локальной медиатеке, как это делает Медиа Агрегатор http://xbmc.ru/forum/showthread.php?t=10592 ?

**Comment by BondarenkoArtur** [comment]
Большинство плагинов в текущий момент в состоянии свободного падения.
Есть люди которым это интересно и они добавляют какой-то функционал / исправляют нерабочие плагины.
Вероятнее всего ваши предложения выполнены не будут, так как этот плагин (как и многие другие) сейчас не особо развивается. Последние изменения были в начале мая, а до этого в конце марта.
Я лично не уверен, что вы найдете программиста, который вам добавит нужный функционал, по-этому предлагаю вам попробовать самому, и предоставить pull-request.

P.S. Я не являюсь основным мейнтейнером в проекте и все высказанное выше моё _личное мнение_
