### ISSUE TITLE
plugin.video.shikimori.org  SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by iG8R** [seppius-xbmc-repo/ru#47]
C недавних пор плагин стал выдавать ошибку:
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>

Починилось путем отключения проверки сертификата:
```
def GetHTML(url):
    certoff = ssl.create_default_context()
    certoff.check_hostname = False
    certoff.verify_mode = ssl.CERT_NONE
    cookieJar = cookielib.CookieJar()
    opener = urllib2.build_opener(urllib2.HTTPSHandler(context=certoff),  urllib2.HTTPCookieProcessor(cookieJar))
    connection = opener.open(url)
    html = connection.read()
    connection.close()
    return html
```

Но как-то это не совсем правильно.
Может быть у кого-то будут лучше идеи, каким образом сделать так, чтобы и плагин работал, и проверка сертификата проходила успешно?

**Comment by sshnaidm** [comment]
Возможно проблема в устаревших(?) сертификатах на девайсе где бежит скрипт. На сайте все нормально и у меня работает валидация без проблем.

**Comment by iG8R** [comment]
Вот все сертификаты, которые имеются на той машине:

![cert_2017-08-10_211937](https://user-images.githubusercontent.com/11407417/29185466-fd91318a-7e11-11e7-9172-cc5a562ecdb0.png)
![cert_2017-08-10_212004](https://user-images.githubusercontent.com/11407417/29185467-fd92f204-7e11-11e7-8efb-4d1985fe4500.png)
![cert_2017-08-10_211902](https://user-images.githubusercontent.com/11407417/29185465-fd8e6b08-7e11-11e7-9e60-30845ea1cc59.png)
![cert_2017-08-10_211841](https://user-images.githubusercontent.com/11407417/29185463-fd8d2cac-7e11-11e7-9a43-77bfb27a557f.png)
![cert_2017-08-10_211802](https://user-images.githubusercontent.com/11407417/29185464-fd8db104-7e11-11e7-857f-423d865421f6.png)

Причем, они абсолютно те же, что и были до возникновения проблемы с плагином, хотя даты устаревших сертификатов никак не соотносятся с недавними датами.

**Comment by vlmaksime** [comment]
@iG8R, грешу на сертификат, идущий с модулем urllib2.
 И еще Вы не указали версию KODI.

**Comment by iG8R** [comment]
Cпасибо, что помогаете с разрешением данной ситуации.
Данная проблема возникла примерно неделю назад, до этого работало все стабильно.
Kodi v17.3 "Krypton" (32bit), затем устновил поверх него Kodi v18 "Leia" nightly (KodiSetup-20170806-1f395332e3-master-x86.exe), но это ничем не помогло, потому откатился обратно на 17.3.
Подскажите, где лежит данный сертификат, т.к. самостоятельно я его что-то не нашел - искал везде по ключевым словам "cert" и "pem", в диретокрии и поддиректориях "Kodi\system\python\" тоже ничего соотвествующего нет.

**Comment by vlmaksime** [comment]
за работу с ssl отвечает модуль "system\python\Lib\ssl.py", который обращается к модулю "\system\python\DLLs\_ssl.pyd". Может сертификат вшит в последнем...
У Вас на устройстве дата и время правильно настроено?

**Comment by iG8R** [comment]
Хм, странно, но DLLs_ssl.pyd я вообще у себя не нашел. Посмотрел на дерево файлов каталога Kodi - в system оно вообще не изменялось с момента установки Kodi, т.е. этого файла вообще никогда у меня и не было, хотя до этого работало все нормально.
Дату я проверил в первую очередь - она синхронизируется каждые 15 минут.
