### ISSUE TITLE
kino-live.org -> kino-live2.org

### ISSUE THREAD

**Issue by DrSatyr** [seppius-xbmc-repo/ru#5]
plugin don't work, domain name is kino-live2.org now!

**Comment by xbmcrepo** [comment]
updated 1.7.6


>Пятница, 23 октября 2015, 3:50 -07:00 от Alexander <notifications@github.com>:
>
>plugin don't work, domain name is kino-live2.org now!
>—
>Reply to this email directly or  view it on GitHub .


С уважением,
Владимир
-- 
bigbax
