### ISSUE TITLE
plugin.video.megogo.net 1.0.4

### ISSUE THREAD

**Issue by bigbax** [seppius-xbmc-repo/ru#56]
Плагин не проходит авторизацию. Лог:
https://pastebin.com/HKKj0uBQ
Сайт megogo.net переехал на https://megogo.ru/ru
Хотя это не имеет значения, а вот капча на сайте - это может быть

**Comment by aleksandria** [comment]
сб, 22 дек. 2018 г., 21:49 bigbax notifications@github.com:
